'use client'
import Image from "next/image";
import styles from "../src/app/page.module.css";
import { NavBar } from "../comps/navbar";
import styled from "styled-components";
import { createContext } from 'react';
import Head from "next/head";

const Container = styled.div`
    display: flex;
    flex-direction: column;
    width:100vw;
    height:100vh;
    padding:0;
    margin:0;
    background-color: #DBA1E6;
    overflow-x: hidden;
`

export default function Home() {
    return (
        <Container>
            <Head>
                <title>About</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/profile.jpg" />
            </Head>
            <NavBar/>
        </Container> 
    )
}