'use client'
import Image from "next/image";
import styles from "../src/app/page.module.css";
import { NavBar } from "../comps/navbar";
import styled from "styled-components";
import { createContext } from 'react';
import { useRouter } from 'next/navigation';
import Link from "next/link";
import Head from "next/head";


const LogoImage1 = styled.img`
width:50%;
  @media (max-width: 769px) {
width:auto;
height:100%;
position:absolute;
left:-90%;
z-index:0;
}
`
const LogoImage2 = styled.img`
  @media (max-width: 769px) {
width:400px;
height:auto;
z-index:2;
}
`

const Divider = styled.div`
display:flex;
flex-direction:row;
width:100%;
align-items:center;
height:100%;
`

const Divider2 = styled.div`
display:flex;
flex-direction:column;
align-items:center;
width:100%;
`

const Button = styled.button`
background-color:#FFD63D;

padding:10px 15px;
font-weight:600;
font-size:30px;
cursor:pointer;
font-family: Kinder, sans-serif;
border: 3px solid #1E152A;
color:#1E152A;
box-shadow: 0.1em 0.1em;

&:hover {
  transform: translate(-0.05em, -0.05em);
  box-shadow: 0.15em 0.15em;
}

&:active {
  transform: translate(0.05em, 0.05em);
    box-shadow: 0.05em 0.05em;
}

  @media (max-width: 769px) {
font-size:24px;
}
`
const Context = createContext()


export default function Landing() {
  const router = useRouter();

  return (
    <main className={styles.main}>
      <Head>
        <title>Wojak Is Cumming - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/profile.jpg" />
      </Head>
      <Divider>
        <LogoImage1 src='/ass.PNG' alt = "logo"/>
        <Divider2>
          <LogoImage2 src='/logo.PNG' alt = "logo"/>  
          
          <Button onClick={() => router.push('/home')}>CUM INSIDE</Button>

        </Divider2>
      </Divider>

    </main>
  );
}
